### ISSUE TITLE
Lambda ERR >> Failure creating alarm: list index out of range

### ISSUE THREAD

**Issue by ahag93** [aws-samples/amazon-cloudwatch-auto-alarms#15]
I Have this issue with my Windows platform and Basic CWAgent Namespace :

`[ERROR] IndexError: list index out of range Traceback (most recent call last):   File "/var/task/cw_auto_alarms.py", line 145, in lambda_handler     process_alarm_tags(instance_id, instance_info, default_alarms, metric_dimensions_map, sns_topic_arn,   File "/var/task/actions.py", line 205, in process_alarm_tags     create_alarm_from_tag(instance_id, alarm_tag, instance_info, metric_dimensions_map, sns_topic_arn, alarm_separator)   File "/var/task/actions.py", line 165, in create_alarm_from_tag     val = additional_dimensions[num * 2 + 1]`

 ????
Thanks !

**Comment by michaelallcloud** [comment]
Same issue here

**Comment by traveltek-tmalek** [comment]
Hey I am getting a similar issue. Did you ever figure this out?

**Comment by will62185** [comment]
Hi @traveltek-tmalek, I'm currently getting the same issue. I've been debugging it, and it seems that I get that error when using a custom namespace other than `CWAgent`.
